# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeSample

  target 'CodeSampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'CodeSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
